/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buspariwisata;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author xatalie
 */
public class BusPariwisata extends javax.swing.JFrame {
    public Database database;
    public Utama utama;
    
    public Player ply;
    public BusPariwisata() {
        initComponents();
        setLocationRelativeTo(null);
        database=new Database();
        setResizable(false);
    }
    public void login(){
        PreparedStatement pr;
        try{
            pr = database.conn.prepareStatement("select * from login");
            ResultSet rs = pr.executeQuery();
            while(rs.next()){
                if(rs.getString(2).equals(tfusername.getText())&&rs.getString(3).equals(tfpassword.getText())){
                    JOptionPane.showMessageDialog(null, "Selamat Datang");
                    this.dispose();
                    utama = new Utama();
                    utama.setVisible(true);
                    utama.setLocationRelativeTo(null);
                    soundClick();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Gagal");
                    System.out.println("Gagal");
                }
            }
        }catch(Exception e){
            System.out.println("Belum Terkoneksi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        pt = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        button = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        tfpassword = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        judul.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        judul.setText("Pemesanan Bus Pariwisata");
        jPanel1.add(judul);
        judul.setBounds(20, 20, 282, 26);

        pt.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        pt.setText("PT. Lancar Jaya");
        jPanel1.add(pt);
        pt.setBounds(20, 50, 120, 17);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buspariwisata/buslogo.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(320, 10, 70, 70);

        username.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        username.setText("Username");
        jPanel1.add(username);
        username.setBounds(30, 120, 80, 19);

        password.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        password.setText("Password");
        jPanel1.add(password);
        password.setBounds(30, 180, 90, 19);

        button.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button.setText("Submit");
        button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });
        jPanel1.add(button);
        button.setBounds(150, 230, 220, 30);

        tfusername.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jPanel1.add(tfusername);
        tfusername.setBounds(150, 120, 220, 30);
        jPanel1.add(tfpassword);
        tfpassword.setBounds(150, 169, 220, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buspariwisata/back.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 410, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_buttonMouseClicked
    private static void soundClick() throws JavaLayerException{
        try{
            String path=null;
            path = System.getProperty("user.dir")+"/src/buspariwisata/click.mp3";
            FileInputStream fis = new FileInputStream(path);
            
            Player ply = new Player(fis);
            ply.play();
            new Thread(){
                @Override
                public void run() {
                    try {
                        ply.play();//To change body of generated methods, choose Tools | Templates.
                    } catch (JavaLayerException ex) {
                        Logger.getLogger(BusPariwisata.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
            }.start();
        }catch(FileNotFoundException e){
            
        }
         
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel password;
    private javax.swing.JLabel pt;
    private javax.swing.JPasswordField tfpassword;
    private javax.swing.JTextField tfusername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
