/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buspariwisata;

/**
 *
 * @author xatalie
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        pt = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        judul.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        judul.setText("Pemesanan Bus Pariwisata");
        jPanel1.add(judul);
        judul.setBounds(90, 20, 282, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buspariwisata/buslogo.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(10, 10, 70, 70);

        pt.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        pt.setText("PT. Lancar Jaya");
        jPanel1.add(pt);
        pt.setBounds(90, 50, 130, 17);

        loadingbar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        loadingbar.setStringPainted(true);
        jPanel1.add(loadingbar);
        loadingbar.setBounds(40, 110, 310, 22);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buspariwisata/back.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 390, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Main m = new Main();
            m.setVisible(true);
            try{
                for(int i=0;i<101;i++){
                    Thread.sleep(70);
                    m.loadingbar.setValue(i);
                    if(i==100){
                        m.setVisible(false);
                        new BusPariwisata().setVisible(true);
                    }
                }
            }catch(Exception e){
                    
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    public static javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pt;
    // End of variables declaration//GEN-END:variables
}
