/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buspariwisata;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xatalie
 */
public class UbahPesanBus extends javax.swing.JFrame {
    public Database database;
    
    BusPariwisata b;
    JadwalBus u;
    /**
     * Creates new form Utama
     */
    public UbahPesanBus() {
        initComponents();
        database=new Database();
        tfnama.setText(u.nama);
        tfalamat.setText(u.alamat);
        tftlp.setText(u.nohp);
        tfharga.setText(Integer.toString(u.harga));
        tftujuan.setText(u.tujuan);
        tftglber.setText(u.tglberangkat);
        tfharga.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        pt = new javax.swing.JLabel();
        btnpesan = new javax.swing.JLabel();
        btnjadwal = new javax.swing.JLabel();
        btnout = new javax.swing.JLabel();
        btnhome = new javax.swing.JLabel();
        labDaf = new javax.swing.JLabel();
        tfalamat = new javax.swing.JTextField();
        labalamat = new javax.swing.JLabel();
        tftlp = new javax.swing.JTextField();
        labtlp = new javax.swing.JLabel();
        tftujuan = new javax.swing.JTextField();
        labtujuan = new javax.swing.JLabel();
        tftglber = new javax.swing.JTextField();
        labtglber = new javax.swing.JLabel();
        labtipe = new javax.swing.JLabel();
        tfharga = new javax.swing.JTextField();
        labharga = new javax.swing.JLabel();
        labnama = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        btncekharga = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();
        btntambah = new javax.swing.JLabel();
        jbtipebus = new javax.swing.JComboBox<>();
        jbjmlbus = new javax.swing.JComboBox<>();
        nav = new javax.swing.JLabel();
        backnav = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        jPanel1.setLayout(null);

        judul.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        judul.setText("Pemesanan Bus Pariwisata");
        jPanel1.add(judul);
        judul.setBounds(90, 10, 340, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buspariwisata/buslogo.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(20, 0, 66, 70);

        pt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        pt.setText("PT. Lancar Jaya");
        jPanel1.add(pt);
        pt.setBounds(90, 40, 170, 20);

        btnpesan.setBackground(new java.awt.Color(255, 255, 255));
        btnpesan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnpesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnpesan.setText("Pemesanan Bus");
        btnpesan.setAlignmentX(2.0F);
        btnpesan.setAlignmentY(2.0F);
        btnpesan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnpesan.setOpaque(true);
        btnpesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpesanMouseClicked(evt);
            }
        });
        jPanel1.add(btnpesan);
        btnpesan.setBounds(190, 90, 130, 20);

        btnjadwal.setBackground(new java.awt.Color(255, 255, 255));
        btnjadwal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnjadwal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjadwal.setText("Jadwal Bus");
        btnjadwal.setAlignmentX(2.0F);
        btnjadwal.setAlignmentY(2.0F);
        btnjadwal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnjadwal.setOpaque(true);
        btnjadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjadwalMouseClicked(evt);
            }
        });
        jPanel1.add(btnjadwal);
        btnjadwal.setBounds(90, 90, 90, 20);

        btnout.setBackground(new java.awt.Color(255, 255, 255));
        btnout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnout.setText("Logout");
        btnout.setAlignmentX(2.0F);
        btnout.setAlignmentY(2.0F);
        btnout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnout.setOpaque(true);
        btnout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnoutMouseClicked(evt);
            }
        });
        jPanel1.add(btnout);
        btnout.setBounds(650, 90, 60, 20);

        btnhome.setBackground(new java.awt.Color(255, 255, 255));
        btnhome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnhome.setText("Home");
        btnhome.setAlignmentX(2.0F);
        btnhome.setAlignmentY(2.0F);
        btnhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhome.setOpaque(true);
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(20, 90, 60, 20);

        labDaf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labDaf.setForeground(new java.awt.Color(255, 255, 255));
        labDaf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDaf.setText("Pemesanan Bus");
        labDaf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(labDaf);
        labDaf.setBounds(20, 130, 680, 30);

        tfalamat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(tfalamat);
        tfalamat.setBounds(300, 220, 230, 30);

        labalamat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labalamat.setForeground(new java.awt.Color(255, 255, 255));
        labalamat.setText("Alamat");
        jPanel1.add(labalamat);
        labalamat.setBounds(30, 220, 100, 22);

        tftlp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(tftlp);
        tftlp.setBounds(300, 260, 230, 30);

        labtlp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labtlp.setForeground(new java.awt.Color(255, 255, 255));
        labtlp.setText("No Telepon");
        jPanel1.add(labtlp);
        labtlp.setBounds(30, 260, 100, 22);

        tftujuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(tftujuan);
        tftujuan.setBounds(300, 420, 230, 30);

        labtujuan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labtujuan.setForeground(new java.awt.Color(255, 255, 255));
        labtujuan.setText("Tujuan");
        jPanel1.add(labtujuan);
        labtujuan.setBounds(30, 420, 100, 22);

        tftglber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(tftglber);
        tftglber.setBounds(300, 460, 230, 30);

        labtglber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labtglber.setForeground(new java.awt.Color(255, 255, 255));
        labtglber.setText("Tanggal Berangkat");
        jPanel1.add(labtglber);
        labtglber.setBounds(30, 460, 140, 22);

        labtipe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labtipe.setForeground(new java.awt.Color(255, 255, 255));
        labtipe.setText("Tipe Bus / Jumlah Bus");
        jPanel1.add(labtipe);
        labtipe.setBounds(30, 300, 180, 22);

        tfharga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(tfharga);
        tfharga.setBounds(300, 380, 230, 30);

        labharga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labharga.setForeground(new java.awt.Color(255, 255, 255));
        labharga.setText("Harga");
        jPanel1.add(labharga);
        labharga.setBounds(30, 380, 130, 22);

        labnama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labnama.setForeground(new java.awt.Color(255, 255, 255));
        labnama.setText("Nama");
        jPanel1.add(labnama);
        labnama.setBounds(30, 180, 100, 22);

        tfnama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(tfnama);
        tfnama.setBounds(300, 180, 230, 30);

        btncekharga.setBackground(new java.awt.Color(255, 255, 255));
        btncekharga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btncekharga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncekharga.setText("Cek Harga");
        btncekharga.setAlignmentX(2.0F);
        btncekharga.setAlignmentY(2.0F);
        btncekharga.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncekharga.setOpaque(true);
        btncekharga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncekhargaMouseClicked(evt);
            }
        });
        jPanel1.add(btncekharga);
        btncekharga.setBounds(560, 180, 140, 20);

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnback.setText("Kembali");
        btnback.setAlignmentX(2.0F);
        btnback.setAlignmentY(2.0F);
        btnback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnback.setOpaque(true);
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(570, 90, 70, 20);

        btntambah.setBackground(new java.awt.Color(255, 255, 255));
        btntambah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btntambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btntambah.setText("Pesan Bus");
        btntambah.setAlignmentX(2.0F);
        btntambah.setAlignmentY(2.0F);
        btntambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btntambah.setOpaque(true);
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntambahMouseClicked(evt);
            }
        });
        jPanel1.add(btntambah);
        btntambah.setBounds(560, 470, 140, 20);

        jbtipebus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtipebus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Damri", "Mulia" }));
        jPanel1.add(jbtipebus);
        jbtipebus.setBounds(300, 300, 100, 30);

        jbjmlbus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbjmlbus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "60", "40" }));
        jPanel1.add(jbjmlbus);
        jbjmlbus.setBounds(430, 300, 100, 30);

        nav.setBackground(new java.awt.Color(51, 51, 51));
        nav.setOpaque(true);
        jPanel1.add(nav);
        nav.setBounds(0, 80, 720, 40);

        backnav.setOpaque(true);
        jPanel1.add(backnav);
        backnav.setBounds(0, 0, 720, 80);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buspariwisata/ground.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 720, 540);

        jMenu1.setText("File");

        jMenuItem2.setText("Pesan Bus");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Tambah Bus");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Jadwal Bus");
        jMenu1.add(jMenuItem4);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int pil=JOptionPane.showConfirmDialog(null, "Apakah Yakin?","",JOptionPane.YES_NO_OPTION);
        if (pil==JOptionPane.YES_OPTION){
            this.dispose();
        }else{
            
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void btnoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoutMouseClicked
        // TODO add your handling code here:
        int pil=JOptionPane.showConfirmDialog(null, "Apakah Yakin?","",JOptionPane.YES_NO_OPTION);
        if (pil==JOptionPane.YES_OPTION){
            this.dispose();
            new BusPariwisata().setVisible(true);
        }else{
            
        }
        
    }//GEN-LAST:event_btnoutMouseClicked

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Utama().setVisible(true);
    }//GEN-LAST:event_btnhomeMouseClicked

    private void btnpesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesanMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new UbahPesanBus().setVisible(true);
        
    }//GEN-LAST:event_btnpesanMouseClicked

    private void btntambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "UPDATE pesan SET nama='"+tfnama.getText()+"',alamat='"+tfalamat.getText()+"',nohp='"+tftlp.getText()+"',tipebus='"+jbtipebus.getModel().getSelectedItem().toString()+"',jumlahbus='"+jbjmlbus.getModel().getSelectedItem().toString()+"',harga='"+Integer.parseInt(tfharga.getText())+"',tujuan='"+tftujuan.getText()+"',tglberangkat='"+tftglber.getText()+"' WHERE id_pesan='"+u.id+"'";
            PreparedStatement pst;
            pst = database.conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Berhasil");
            JadwalBus utama = new JadwalBus();
            utama.setVisible(true);
            utama.setLocationRelativeTo(null);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
    }//GEN-LAST:event_btntambahMouseClicked

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Utama().setVisible(true);
    }//GEN-LAST:event_btnbackMouseClicked

    private void btncekhargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncekhargaMouseClicked
        // TODO add your handling code here:
        if("Damri".equals(jbtipebus.getModel().getSelectedItem().toString())&&"40".equals(jbjmlbus.getModel().getSelectedItem().toString())){
            tfharga.setText("600000");
//            Integer bayar = Integer.parseInt(tfbayar.getText());
//            Integer sisa;
//            Integer total = Integer.parseInt(tftotal.getText());
//            sisa = total - bayar;
//            tfsisa.setText(sisa.toString());
        }else if("Mulia".equals(jbtipebus.getModel().getSelectedItem().toString())&&"40".equals(jbjmlbus.getModel().getSelectedItem().toString())){
            tfharga.setText("800000");
            
        }else if("Damri".equals(jbtipebus.getModel().getSelectedItem().toString())&&"60".equals(jbjmlbus.getModel().getSelectedItem().toString())){
            tfharga.setText("1200000");
            
        }else if("Mulia".equals(jbtipebus.getModel().getSelectedItem().toString())&&"60".equals(jbjmlbus.getModel().getSelectedItem().toString())){
            tfharga.setText("1400000");
            
        }
        
    }//GEN-LAST:event_btncekhargaMouseClicked

    private void btnjadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjadwalMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new JadwalBus().setVisible(true);
    }//GEN-LAST:event_btnjadwalMouseClicked
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JLabel background;
    private javax.swing.JLabel backnav;
    private javax.swing.JLabel btnback;
    private javax.swing.JLabel btncekharga;
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnjadwal;
    private javax.swing.JLabel btnout;
    private javax.swing.JLabel btnpesan;
    private javax.swing.JLabel btntambah;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jbjmlbus;
    private javax.swing.JComboBox<String> jbtipebus;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel labDaf;
    private javax.swing.JLabel labalamat;
    private javax.swing.JLabel labharga;
    private javax.swing.JLabel labnama;
    private javax.swing.JLabel labtglber;
    private javax.swing.JLabel labtipe;
    private javax.swing.JLabel labtlp;
    private javax.swing.JLabel labtujuan;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nav;
    private javax.swing.JLabel pt;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tftglber;
    private javax.swing.JTextField tftlp;
    private javax.swing.JTextField tftujuan;
    // End of variables declaration//GEN-END:variables
}
