/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buspariwisata;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xatalie
 */
public class Utama extends javax.swing.JFrame {
    public Database database;
    static int id,jml,harga;
    static String tipe,plat;
    BusPariwisata b;
    /**
     * Creates new form Utama
     */
    public Utama() {
        initComponents();
        database=new Database();
        tabelDaftar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        pt = new javax.swing.JLabel();
        btnpesan = new javax.swing.JLabel();
        btnjadwal = new javax.swing.JLabel();
        btnout = new javax.swing.JLabel();
        btnupdate = new javax.swing.JLabel();
        btnhapus = new javax.swing.JLabel();
        btntambah = new javax.swing.JLabel();
        btnhome = new javax.swing.JLabel();
        labEdit = new javax.swing.JLabel();
        labDaf = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tBus = new javax.swing.JTable();
        labedit = new javax.swing.JLabel();
        tfedit = new javax.swing.JTextField();
        nav = new javax.swing.JLabel();
        backnav = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        jPanel1.setLayout(null);

        judul.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        judul.setText("Pemesanan Bus Pariwisata");
        jPanel1.add(judul);
        judul.setBounds(90, 10, 330, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buspariwisata/buslogo.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(20, 0, 66, 70);

        pt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        pt.setText("PT. Lancar Jaya");
        jPanel1.add(pt);
        pt.setBounds(90, 40, 150, 20);

        btnpesan.setBackground(new java.awt.Color(255, 255, 255));
        btnpesan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnpesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnpesan.setText("Pemesanan Bus");
        btnpesan.setAlignmentX(2.0F);
        btnpesan.setAlignmentY(2.0F);
        btnpesan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnpesan.setOpaque(true);
        btnpesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpesanMouseClicked(evt);
            }
        });
        jPanel1.add(btnpesan);
        btnpesan.setBounds(190, 90, 130, 20);

        btnjadwal.setBackground(new java.awt.Color(255, 255, 255));
        btnjadwal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnjadwal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnjadwal.setText("Jadwal Bus");
        btnjadwal.setAlignmentX(2.0F);
        btnjadwal.setAlignmentY(2.0F);
        btnjadwal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnjadwal.setOpaque(true);
        btnjadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjadwalMouseClicked(evt);
            }
        });
        jPanel1.add(btnjadwal);
        btnjadwal.setBounds(90, 90, 90, 20);

        btnout.setBackground(new java.awt.Color(255, 255, 255));
        btnout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnout.setText("Logout");
        btnout.setAlignmentX(2.0F);
        btnout.setAlignmentY(2.0F);
        btnout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnout.setOpaque(true);
        btnout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnoutMouseClicked(evt);
            }
        });
        jPanel1.add(btnout);
        btnout.setBounds(650, 90, 60, 20);

        btnupdate.setBackground(new java.awt.Color(255, 255, 255));
        btnupdate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnupdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnupdate.setText("Update Bus");
        btnupdate.setAlignmentX(2.0F);
        btnupdate.setAlignmentY(2.0F);
        btnupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnupdate.setOpaque(true);
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(560, 480, 140, 20);

        btnhapus.setBackground(new java.awt.Color(255, 255, 255));
        btnhapus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnhapus.setText("Hapus Bus");
        btnhapus.setAlignmentX(2.0F);
        btnhapus.setAlignmentY(2.0F);
        btnhapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhapus.setOpaque(true);
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhapusMouseClicked(evt);
            }
        });
        jPanel1.add(btnhapus);
        btnhapus.setBounds(560, 450, 140, 20);

        btntambah.setBackground(new java.awt.Color(255, 255, 255));
        btntambah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btntambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btntambah.setText("Tambah Bus");
        btntambah.setAlignmentX(2.0F);
        btntambah.setAlignmentY(2.0F);
        btntambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btntambah.setOpaque(true);
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntambahMouseClicked(evt);
            }
        });
        jPanel1.add(btntambah);
        btntambah.setBounds(560, 420, 140, 20);

        btnhome.setBackground(new java.awt.Color(255, 255, 255));
        btnhome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnhome.setText("Home");
        btnhome.setAlignmentX(2.0F);
        btnhome.setAlignmentY(2.0F);
        btnhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnhome.setOpaque(true);
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
        });
        jPanel1.add(btnhome);
        btnhome.setBounds(20, 90, 60, 20);

        labEdit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labEdit.setForeground(new java.awt.Color(255, 255, 255));
        labEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labEdit.setText("Edit");
        labEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(labEdit);
        labEdit.setBounds(560, 170, 140, 30);

        labDaf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labDaf.setForeground(new java.awt.Color(255, 255, 255));
        labDaf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDaf.setText("Daftar Bus");
        labDaf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(labDaf);
        labDaf.setBounds(20, 130, 530, 30);

        tBus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID Bus", "Tipe Bus", "Plat", "Jumlah Kursi", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tBus);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 530, 330);

        labedit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labedit.setForeground(new java.awt.Color(255, 255, 255));
        labedit.setText("Edit ID ke-");
        jPanel1.add(labedit);
        labedit.setBounds(560, 220, 80, 17);

        tfedit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(tfedit);
        tfedit.setBounds(560, 240, 140, 30);

        nav.setBackground(new java.awt.Color(51, 51, 51));
        nav.setOpaque(true);
        jPanel1.add(nav);
        nav.setBounds(0, 80, 720, 40);

        backnav.setOpaque(true);
        jPanel1.add(backnav);
        backnav.setBounds(0, 0, 720, 80);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buspariwisata/ground.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 720, 540);

        jMenu1.setText("File");

        jMenuItem2.setText("Pesan Bus");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Tambah Bus");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Jadwal Bus");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int pil=JOptionPane.showConfirmDialog(null, "Apakah Yakin?","",JOptionPane.YES_NO_OPTION);
        if (pil==JOptionPane.YES_OPTION){
            this.dispose();
        }else{
            
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void btnoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoutMouseClicked
        // TODO add your handling code here:
        int pil=JOptionPane.showConfirmDialog(null, "Apakah Yakin?","",JOptionPane.YES_NO_OPTION);
        if (pil==JOptionPane.YES_OPTION){
            this.dispose();
            new BusPariwisata().setVisible(true);
        }else{
            
        }
        
    }//GEN-LAST:event_btnoutMouseClicked

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Utama().setVisible(true);
    }//GEN-LAST:event_btnhomeMouseClicked

    private void btntambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new TambahBus().setVisible(true);
    }//GEN-LAST:event_btntambahMouseClicked

    private void btnhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseClicked
        // TODO add your handling code here:
        int pil=JOptionPane.showConfirmDialog(null, "Apakah Yakin?","",JOptionPane.YES_NO_OPTION);
        if (pil==JOptionPane.YES_OPTION){
            
            try {
                String sql = "DELETE FROM bus WHERE id_bus=?";
                PreparedStatement pst;
                pst = database.conn.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(tfedit.getText()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Delete Berhasil");
                Utama utama = new Utama();
                utama.setVisible(true);
                utama.setLocationRelativeTo(null);
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Inputkan ID ke-");
            }
        }else{
            
        }
    }//GEN-LAST:event_btnhapusMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        // TODO add your handling code here:
        try{
            String sql = "select * from bus where id_bus=?";
            PreparedStatement pst;
            pst = database.conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(tfedit.getText()));
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                Object o[] = {
                    id=Integer.parseInt(rs.getString("id_bus")),
                    tipe=rs.getString("tipe_bus"), 
                    plat=rs.getString("plat"),
                    jml=rs.getInt(4),
                    harga=rs.getInt(5),
                };
            }
            UbahBus u = new UbahBus();
            u.setVisible(true);
            u.setLocationRelativeTo(null);
            this.dispose();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Inputkan ID ke-");
        }
        
    }//GEN-LAST:event_btnupdateMouseClicked

    private void btnpesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesanMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new PesanBus().setVisible(true);
        
    }//GEN-LAST:event_btnpesanMouseClicked

    private void btnjadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjadwalMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new JadwalBus().setVisible(true);
    }//GEN-LAST:event_btnjadwalMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new PesanBus().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new TambahBus().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new JadwalBus().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    private void tabelDaftar(){
        PreparedStatement ps;
        DefaultTableModel model = (DefaultTableModel) tBus.getModel();
        
        try{
            ps = database.conn.prepareStatement("select * from bus");
            ResultSet rs = ps.executeQuery();
            int no = 1;
            while(rs.next()){
                Object o[] = {
                    no++, 
                    rs.getString("id_bus"),
                    rs.getString("tipe_bus"), 
                    rs.getString("plat"),
                    rs.getString("jumlah_kursi"),
                    rs.getString("harga"),
                };
                model.addRow(o); 
            }     
        }catch (Exception e){
            
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JLabel background;
    private javax.swing.JLabel backnav;
    private javax.swing.JLabel btnhapus;
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnjadwal;
    private javax.swing.JLabel btnout;
    private javax.swing.JLabel btnpesan;
    private javax.swing.JLabel btntambah;
    private javax.swing.JLabel btnupdate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel labDaf;
    private javax.swing.JLabel labEdit;
    private javax.swing.JLabel labedit;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nav;
    private javax.swing.JLabel pt;
    private javax.swing.JTable tBus;
    private javax.swing.JTextField tfedit;
    // End of variables declaration//GEN-END:variables
}
